name: Weather Data App Deployment

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '13'
          distribution: 'adopt'

      - name: Compile Application
        run: javac -d . src/com/mpda/CurrentConditionsDisplay.java src/com/mpda/Main.java src/com/mpda/Observer.java src/com/mpda/StatisticsDisplay.java src/com/mpda/Subject.java src/com/mpda/WeatherData.java

      - name: Run Application
        run: java -cp . com.mpda.Main
