name: Unit Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK and JUnit Jupiter
        uses: actions/setup-java@v1
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compile and run tests
        run: |
          javac -cp .:lib/* src/com/mpda/*.java
          java -cp .:lib/*:src com.mpda.WeatherDataTest
