name: Unit Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Compile application
        run: javac -cp .:.github/lib/apiguardian-api-1.1.2.jar:.github/lib/junit-jupiter-api-5.9.2.jar:.github/lib/junit-jujpiter-engine-5.9.2.jar:.github/lib/junit-platform-commons-1.9.2.jar:.github/lib/junit-platform-engine-1.9.2.jar:.github/lib/opentest4j-1.2.0.jar src/com/mpda/*.java

      - name: Run tests
        run: java -cp .:.github/lib/*:src com.mpda.WeatherDataTest
